
print("Add : ", 5 + 9)
print("Sub : ", 5 - 9)
print("Mul : ", 5 * 9)
print("Div : ", 5 / 9)
print("Mod : ", 5 % 9)
print("Int Div : ", 5 // 9)
print("Power : ", 2 ** 3)
print("Equation  : ", 1 + 8 * 9)
print("Equation  : ", (1 + 8) * 9)